# -*- coding: utf-8 -*-
"""LiteQ-STHNet: A Lightweight Quantum- Driven Contrastive Multimodal Hypergraph Framework for Early Major Depressive Disorder Detection  with Intelligent Chatbot-Based Intervention system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yiUwI-G5YhdrbvM7kJXLviDH6lzGpFEm
"""

# ==========================================================
# LiteQ-STHNet - PART 1
# Multimodal Dataset Loading + Preprocessing
# ==========================================================

# Install (Run once in Colab)
# !pip install librosa vaderSentiment nltk soundfile -q

import os
import glob
import re
import librosa
import numpy as np
import pandas as pd
import nltk

from tqdm import tqdm
from scipy.signal import medfilt
from sklearn.preprocessing import MinMaxScaler, StandardScaler

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

# ==========================================================
# Download NLTK Resources
# ==========================================================

nltk.download("punkt")
nltk.download("stopwords")

stop_words = set(stopwords.words("english"))
analyzer = SentimentIntensityAnalyzer()

# ==========================================================
# DATASET PATHS (CHANGE THESE)
# ==========================================================

TEXT_PATH = "/content/datasets/text"
SPEECH_PATH = "/content/datasets/speech"
PHYSIO_PATH = "/content/datasets/physiological"
BEHAVIOR_PATH = "/content/datasets/behavioral"

SAVE_PATH = "/content/processed"

os.makedirs(SAVE_PATH, exist_ok=True)

# ==========================================================
# TEXT PREPROCESSING
# ==========================================================

def clean_text(text):

    text = str(text).lower()

    text = re.sub(r"http\S+", "", text)

    text = re.sub(r"[^a-z ]", " ", text)

    tokens = word_tokenize(text)

    tokens = [w for w in tokens if w not in stop_words]

    return " ".join(tokens)


def sentiment(text):

    return analyzer.polarity_scores(text)["compound"]


print("Loading Text Dataset...")

text_files = glob.glob(os.path.join(TEXT_PATH, "*.csv"))

text_df = pd.concat(
    [pd.read_csv(f) for f in text_files],
    ignore_index=True
)

# Change column name if needed
TEXT_COLUMN = "text"

text_df["clean_text"] = text_df[TEXT_COLUMN].astype(str).apply(clean_text)

text_df["sentiment"] = text_df["clean_text"].apply(sentiment)

# ==========================================================
# SPEECH PREPROCESSING
# ==========================================================

print("Loading Speech Dataset...")

wav_files = glob.glob(
    os.path.join(SPEECH_PATH, "**", "*.wav"),
    recursive=True
)

speech_features = []

for wav in tqdm(wav_files):

    signal, sr = librosa.load(wav, sr=16000)

    signal, _ = librosa.effects.trim(signal)

    mfcc = librosa.feature.mfcc(
        y=signal,
        sr=sr,
        n_mfcc=40
    )

    mfcc = np.mean(mfcc.T, axis=0)

    speech_features.append(mfcc)

speech_df = pd.DataFrame(speech_features)

# ==========================================================
# PHYSIOLOGICAL PREPROCESSING
# ==========================================================

print("Loading Physiological Dataset...")

physio_files = glob.glob(os.path.join(PHYSIO_PATH, "*.csv"))

physio_df = pd.concat(
    [pd.read_csv(f) for f in physio_files],
    ignore_index=True
)

physio_numeric = physio_df.select_dtypes(include=np.number)

physio_numeric = physio_numeric.fillna(physio_numeric.mean())

for col in physio_numeric.columns:

    physio_numeric[col] = medfilt(
        physio_numeric[col],
        kernel_size=3
    )

scaler = MinMaxScaler()

physio_numeric[:] = scaler.fit_transform(physio_numeric)

physio_df = physio_numeric

# ==========================================================
# BEHAVIORAL PREPROCESSING
# ==========================================================

print("Loading Behavioral Dataset...")

behavior_files = glob.glob(os.path.join(BEHAVIOR_PATH, "*.csv"))

behavior_df = pd.concat(
    [pd.read_csv(f) for f in behavior_files],
    ignore_index=True
)

behavior_numeric = behavior_df.select_dtypes(include=np.number)

behavior_numeric = behavior_numeric.fillna(behavior_numeric.mean())

scaler = StandardScaler()

behavior_numeric[:] = scaler.fit_transform(behavior_numeric)

behavior_df = behavior_numeric

# ==========================================================
# SYNCHRONIZE ALL MODALITIES
# ==========================================================

min_samples = min(

    len(text_df),

    len(speech_df),

    len(physio_df),

    len(behavior_df)

)

text_df = text_df.iloc[:min_samples]

speech_df = speech_df.iloc[:min_samples]

physio_df = physio_df.iloc[:min_samples]

behavior_df = behavior_df.iloc[:min_samples]

# ==========================================================
# SAVE
# ==========================================================

text_df.to_csv(
    os.path.join(SAVE_PATH, "processed_text.csv"),
    index=False
)

speech_df.to_csv(
    os.path.join(SAVE_PATH, "processed_speech.csv"),
    index=False
)

physio_df.to_csv(
    os.path.join(SAVE_PATH, "processed_physiological.csv"),
    index=False
)

behavior_df.to_csv(
    os.path.join(SAVE_PATH, "processed_behavior.csv"),
    index=False
)

# ==========================================================
# SUMMARY
# ==========================================================

print("\n====================================")

print("Processed Text Shape          :", text_df.shape)

print("Processed Speech Shape        :", speech_df.shape)

print("Processed Physiological Shape :", physio_df.shape)

print("Processed Behavioral Shape    :", behavior_df.shape)

print("====================================")

print("\nFiles Saved To :", SAVE_PATH)

print("\nPreprocessing Completed Successfully.")

# ==========================================================
# LiteQ-STHNet - PART 2
# Lightweight Modality-Specific Encoders
# ==========================================================

# !pip install transformers torch torchvision -q

import os
import numpy as np
import pandas as pd
import torch
import torch.nn as nn

from transformers import AutoTokenizer, AutoModel

# ==========================================================
# PATHS
# ==========================================================

DATA_PATH = "/content/processed"

SAVE_PATH = "/content/encoded"

os.makedirs(SAVE_PATH, exist_ok=True)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Using Device :", DEVICE)

# ==========================================================
# LOAD DATA
# ==========================================================

text_df = pd.read_csv(DATA_PATH + "/processed_text.csv")

speech_df = pd.read_csv(DATA_PATH + "/processed_speech.csv")

physio_df = pd.read_csv(DATA_PATH + "/processed_physiological.csv")

behavior_df = pd.read_csv(DATA_PATH + "/processed_behavior.csv")

# ==========================================================
# TEXT ENCODER (DistilBERT)
# ==========================================================

print("Loading DistilBERT...")

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

bert = AutoModel.from_pretrained("distilbert-base-uncased").to(DEVICE)

bert.eval()

text_features = []

with torch.no_grad():

    for sentence in text_df["clean_text"].astype(str):

        tokens = tokenizer(
            sentence,
            return_tensors="pt",
            truncation=True,
            padding="max_length",
            max_length=64
        )

        tokens = {k:v.to(DEVICE) for k,v in tokens.items()}

        output = bert(**tokens)

        feature = output.last_hidden_state[:,0,:]

        text_features.append(feature.squeeze().cpu().numpy())

text_features = np.array(text_features)

print("Text Feature Shape :", text_features.shape)

# ==========================================================
# LIGHTWEIGHT CNN ENCODER
# ==========================================================

class LightweightEncoder(nn.Module):

    def __init__(self,input_dim):

        super().__init__()

        self.network = nn.Sequential(

            nn.Linear(input_dim,256),

            nn.ReLU(),

            nn.Dropout(0.2),

            nn.Linear(256,256),

            nn.ReLU()

        )

    def forward(self,x):

        return self.network(x)

# ==========================================================
# SPEECH ENCODER
# ==========================================================

speech_encoder = LightweightEncoder(speech_df.shape[1]).to(DEVICE)

speech_tensor = torch.tensor(
    speech_df.values,
    dtype=torch.float32
).to(DEVICE)

with torch.no_grad():

    speech_features = speech_encoder(speech_tensor).cpu().numpy()

print("Speech Feature Shape :", speech_features.shape)

# ==========================================================
# PHYSIOLOGICAL ENCODER
# ==========================================================

physio_encoder = LightweightEncoder(
    physio_df.shape[1]
).to(DEVICE)

physio_tensor = torch.tensor(
    physio_df.values,
    dtype=torch.float32
).to(DEVICE)

with torch.no_grad():

    physio_features = physio_encoder(
        physio_tensor
    ).cpu().numpy()

print("Physio Feature Shape :", physio_features.shape)

# ==========================================================
# BEHAVIORAL ENCODER
# ==========================================================

behavior_encoder = LightweightEncoder(
    behavior_df.shape[1]
).to(DEVICE)

behavior_tensor = torch.tensor(
    behavior_df.values,
    dtype=torch.float32
).to(DEVICE)

with torch.no_grad():

    behavior_features = behavior_encoder(
        behavior_tensor
    ).cpu().numpy()

print("Behavior Feature Shape :", behavior_features.shape)

# ==========================================================
# SHARED PROJECTION LAYER
# ==========================================================

projection = nn.Linear(256,256).to(DEVICE)

def project(features):

    x = torch.tensor(
        features,
        dtype=torch.float32
    ).to(DEVICE)

    with torch.no_grad():

        x = projection(x)

    return x.cpu().numpy()

text_proj = project(text_features)

speech_proj = project(speech_features)

physio_proj = project(physio_features)

behavior_proj = project(behavior_features)

# ==========================================================
# MULTIMODAL FUSION
# ==========================================================

fusion = np.concatenate(

    [

        text_proj,

        speech_proj,

        physio_proj,

        behavior_proj

    ],

    axis=1

)

print()

print("===================================")

print("Text      :", text_proj.shape)

print("Speech    :", speech_proj.shape)

print("Physio    :", physio_proj.shape)

print("Behavior  :", behavior_proj.shape)

print("-----------------------------------")

print("Fusion    :", fusion.shape)

print("===================================")

# ==========================================================
# SAVE FEATURES
# ==========================================================

np.save(

    SAVE_PATH + "/text_features.npy",

    text_proj

)

np.save(

    SAVE_PATH + "/speech_features.npy",

    speech_proj

)

np.save(

    SAVE_PATH + "/physio_features.npy",

    physio_proj

)

np.save(

    SAVE_PATH + "/behavior_features.npy",

    behavior_proj

)

np.save(

    SAVE_PATH + "/multimodal_fusion.npy",

    fusion

)

pd.DataFrame(fusion).to_csv(

    SAVE_PATH + "/multimodal_fusion.csv",

    index=False

)

print()

print("Encoded Features Saved Successfully.")

print("Save Path :", SAVE_PATH)

# ==========================================================
# LiteQ-STHNet - PART 3A-1
# Quantum-Assisted Contrastive Learning
# Quantum Feature Mapping
# ==========================================================

# Install (Run once in Google Colab)
# !pip install pennylane torch -q

import os
import numpy as np
import pandas as pd
import pennylane as qml
import torch
import torch.nn as nn
import torch.optim as optim

from torch.utils.data import Dataset, DataLoader

# ==========================================================
# DEVICE
# ==========================================================

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Device :", DEVICE)

# ==========================================================
# LOAD MULTIMODAL FEATURES
# ==========================================================

FEATURE_PATH = "/content/encoded/multimodal_fusion.npy"

features = np.load(FEATURE_PATH)

print("Fusion Shape :", features.shape)

# ==========================================================
# NORMALIZATION
# ==========================================================

features = (features - features.mean(axis=0)) / (features.std(axis=0) + 1e-8)

# ==========================================================
# PARAMETERS
# ==========================================================

N_QUBITS = 8

N_LAYERS = 4

EMBED_DIM = 256

# ==========================================================
# REDUCE FEATURE DIMENSION
# ==========================================================

projection = nn.Linear(
    features.shape[1],
    N_QUBITS
).to(DEVICE)

with torch.no_grad():

    reduced = projection(
        torch.tensor(
            features,
            dtype=torch.float32
        ).to(DEVICE)
    )

reduced = reduced.cpu().numpy()

print("Reduced Shape :", reduced.shape)

# ==========================================================
# PENNYLANE DEVICE
# ==========================================================

dev = qml.device(
    "default.qubit",
    wires=N_QUBITS
)

# ==========================================================
# QUANTUM FEATURE MAP
# ==========================================================

def feature_map(x):

    for i in range(N_QUBITS):

        qml.RY(x[i], wires=i)

    for i in range(N_QUBITS-1):

        qml.CNOT(
            wires=[i,i+1]
        )

# ==========================================================
# VARIATIONAL LAYER
# ==========================================================

def variational_layer(weights):

    for i in range(N_QUBITS):

        qml.RX(weights[i][0], wires=i)

        qml.RY(weights[i][1], wires=i)

        qml.RZ(weights[i][2], wires=i)

    for i in range(N_QUBITS-1):

        qml.CNOT(
            wires=[i,i+1]
        )

# ==========================================================
# QUANTUM CIRCUIT
# ==========================================================

@qml.qnode(dev, interface="torch")

def quantum_circuit(x, weights):

    feature_map(x)

    for layer in weights:

        variational_layer(layer)

    return [
        qml.expval(qml.PauliZ(i))
        for i in range(N_QUBITS)
    ]

# ==========================================================
# INITIALIZE TRAINABLE PARAMETERS
# ==========================================================

weights = torch.nn.Parameter(

    0.01 * torch.randn(
        N_LAYERS,
        N_QUBITS,
        3
    )

)

print("Weights Shape :", weights.shape)

# ==========================================================
# TEST CIRCUIT
# ==========================================================

sample = torch.tensor(
    reduced[0],
    dtype=torch.float32
)

output = quantum_circuit(
    sample,
    weights
)

output = torch.stack(output)

print()

print("Quantum Output Shape :", output.shape)

print(output)

# ==========================================================
# LiteQ-STHNet - PART 3A-2
# Quantum Encoder + Contrastive Learning
# ==========================================================

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

# ==========================================================
# QUANTUM ENCODER
# ==========================================================

class QuantumEncoder(nn.Module):

    def __init__(self):

        super().__init__()

        self.weights = nn.Parameter(

            0.01 * torch.randn(
                N_LAYERS,
                N_QUBITS,
                3
            )
        )

    def forward(self, x):

        outputs = []

        for sample in x:

            q_out = quantum_circuit(
                sample,
                self.weights
            )

            q_out = torch.stack(q_out)

            outputs.append(q_out)

        return torch.stack(outputs)

# ==========================================================
# DATASET
# ==========================================================

class ContrastiveDataset(Dataset):

    def __init__(self, data):

        self.data = torch.tensor(
            data,
            dtype=torch.float32
        )

    def __len__(self):

        return len(self.data)

    def __getitem__(self, idx):

        x = self.data[idx]

        noise1 = torch.randn_like(x) * 0.05
        noise2 = torch.randn_like(x) * 0.05

        view1 = x + noise1
        view2 = x + noise2

        return view1, view2

# ==========================================================
# DATA LOADER
# ==========================================================

dataset = ContrastiveDataset(reduced)

loader = DataLoader(
    dataset,
    batch_size=32,
    shuffle=True
)

print("Total Samples :", len(dataset))

# ==========================================================
# NT-XENT LOSS
# ==========================================================

class NTXentLoss(nn.Module):

    def __init__(
        self,
        temperature=0.5
    ):

        super().__init__()

        self.temperature = temperature

    def forward(self, z1, z2):

        batch_size = z1.size(0)

        z1 = F.normalize(z1, dim=1)
        z2 = F.normalize(z2, dim=1)

        representations = torch.cat(
            [z1, z2],
            dim=0
        )

        similarity_matrix = torch.matmul(
            representations,
            representations.T
        )

        mask = torch.eye(
            2 * batch_size,
            dtype=torch.bool
        ).to(similarity_matrix.device)

        similarity_matrix = similarity_matrix[~mask]

        similarity_matrix = similarity_matrix.view(
            2 * batch_size,
            -1
        )

        positives = torch.sum(
            z1 * z2,
            dim=1
        )

        positives = torch.cat(
            [positives, positives],
            dim=0
        )

        logits = torch.cat(
            [
                positives.unsqueeze(1),
                similarity_matrix
            ],
            dim=1
        )

        logits = logits / self.temperature

        labels = torch.zeros(
            logits.shape[0],
            dtype=torch.long
        ).to(logits.device)

        loss = F.cross_entropy(
            logits,
            labels
        )

        return loss

# ==========================================================
# MODEL
# ==========================================================

quantum_encoder = QuantumEncoder().to(DEVICE)

criterion = NTXentLoss(
    temperature=0.5
)

optimizer = torch.optim.Adam(
    quantum_encoder.parameters(),
    lr=1e-3
)

print("\nQuantum Encoder Ready")
print("NT-Xent Loss Ready")
print("Optimizer Ready")

# ==========================================================
# LiteQ-STHNet - PART 3B-1
# Quantum Contrastive Learning Training
# ==========================================================

import torch
import torch.optim as optim
from tqdm import tqdm

# ==========================================================
# HYPERPARAMETERS
# ==========================================================

EPOCHS = 30
LEARNING_RATE = 0.001

optimizer = optim.Adam(

    list(encoder.parameters()) + [weights],

    lr=LEARNING_RATE

)

# ==========================================================
# TRAINING
# ==========================================================

train_losses = []

print("\nStarting Quantum Contrastive Training...\n")

for epoch in range(EPOCHS):

    encoder.train()

    epoch_loss = 0

    loop = tqdm(train_loader)

    for anchor, positive, negative in loop:

        anchor = anchor.to(DEVICE)

        positive = positive.to(DEVICE)

        negative = negative.to(DEVICE)

        optimizer.zero_grad()

        anchor_embedding = encoder(anchor)

        positive_embedding = encoder(positive)

        negative_embedding = encoder(negative)

        loss = nt_xent_loss(

            anchor_embedding,

            positive_embedding,

            negative_embedding,

            temperature=0.5

        )

        loss.backward()

        optimizer.step()

        epoch_loss += loss.item()

        loop.set_description(

            f"Epoch [{epoch+1}/{EPOCHS}]"

        )

        loop.set_postfix(

            Loss=loss.item()

        )

    avg_loss = epoch_loss / len(train_loader)

    train_losses.append(avg_loss)

    print(

        f"Epoch {epoch+1:02d} Loss : {avg_loss:.4f}"

    )

print("\nTraining Completed.")

# ==========================================================
# LiteQ-STHNet - PART 4
# Multimodal Hypergraph Construction
# ==========================================================

# !pip install scikit-learn scipy networkx -q

import os
import numpy as np
import pandas as pd

from sklearn.neighbors import NearestNeighbors
from scipy.sparse import csr_matrix, diags

# ==========================================================
# PATHS
# ==========================================================

FEATURE_PATH = "/content/encoded/quantum_features.npy"

SAVE_PATH = "/content/hypergraph"

os.makedirs(SAVE_PATH, exist_ok=True)

# ==========================================================
# LOAD QUANTUM FEATURES
# ==========================================================

X = np.load(FEATURE_PATH)

print("Quantum Feature Shape :", X.shape)

# ==========================================================
# PARAMETERS
# ==========================================================

K = 10          # number of neighbors

# ==========================================================
# KNN GRAPH
# ==========================================================

nbrs = NearestNeighbors(
    n_neighbors=K,
    metric="euclidean"
)

nbrs.fit(X)

distances, indices = nbrs.kneighbors(X)

# ==========================================================
# BUILD HYPERGRAPH INCIDENCE MATRIX
# ==========================================================

N = X.shape[0]

M = N                     # one hyperedge per sample

H = np.zeros((N, M))

for edge in range(M):

    nodes = indices[edge]

    H[nodes, edge] = 1

print("Incidence Matrix :", H.shape)

# ==========================================================
# HYPEREDGE WEIGHTS
# ==========================================================

W = np.ones(M)

# ==========================================================
# DEGREE MATRICES
# ==========================================================

DV = np.sum(H * W, axis=1)

DE = np.sum(H, axis=0)

DV[DV == 0] = 1

DE[DE == 0] = 1

DV_inv_sqrt = np.diag(1 / np.sqrt(DV))

DE_inv = np.diag(1 / DE)

W_diag = np.diag(W)

# ==========================================================
# NORMALIZED HYPERGRAPH LAPLACIAN
# ==========================================================

G = DV_inv_sqrt @ H @ W_diag @ DE_inv @ H.T @ DV_inv_sqrt

print("Hypergraph Matrix :", G.shape)

# ==========================================================
# SAVE MATRICES
# ==========================================================

np.save(

    SAVE_PATH + "/incidence_matrix.npy",

    H

)

np.save(

    SAVE_PATH + "/hypergraph_matrix.npy",

    G

)

np.save(

    SAVE_PATH + "/vertex_degree.npy",

    DV

)

np.save(

    SAVE_PATH + "/hyperedge_degree.npy",

    DE

)

pd.DataFrame(H).to_csv(

    SAVE_PATH + "/incidence_matrix.csv",

    index=False

)

pd.DataFrame(G).to_csv(

    SAVE_PATH + "/hypergraph_matrix.csv",

    index=False

)

print()

print("====================================")

print("Nodes        :", N)

print("Hyperedges   :", M)

print("Neighbors    :", K)

print("====================================")

print()

print("Saved to :", SAVE_PATH)

print("Hypergraph Construction Completed Successfully.")

# ==========================================================
# LiteQ-STHNet - PART 5A-1.1
# Hypergraph Convolution Layer
# ==========================================================

import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ==========================================================
# LOAD HYPERGRAPH MATRIX
# ==========================================================

HYPERGRAPH_PATH = "/content/hypergraph/hypergraph_matrix.npy"

G = np.load(HYPERGRAPH_PATH)

G = torch.tensor(G, dtype=torch.float32).to(DEVICE)

print("Hypergraph Matrix Shape :", G.shape)

# ==========================================================
# HYPERGRAPH CONVOLUTION LAYER
# ==========================================================

class HypergraphConv(nn.Module):

    def __init__(self,
                 in_channels,
                 out_channels,
                 dropout=0.3):

        super(HypergraphConv, self).__init__()

        self.linear = nn.Linear(
            in_channels,
            out_channels,
            bias=True
        )

        self.batch_norm = nn.BatchNorm1d(
            out_channels
        )

        self.dropout = nn.Dropout(
            dropout
        )

    def forward(self,
                x,
                G):

        # Hypergraph propagation
        x = torch.matmul(G, x)

        # Linear transformation
        x = self.linear(x)

        # Batch Normalization
        x = self.batch_norm(x)

        # Activation
        x = F.relu(x)

        # Dropout
        x = self.dropout(x)

        return x

# ==========================================================
# TEST HYPERGRAPH CONVOLUTION
# ==========================================================

NUM_NODES = G.shape[0]

INPUT_DIM = 256

OUTPUT_DIM = 256

dummy_features = torch.randn(
    NUM_NODES,
    INPUT_DIM
).to(DEVICE)

hgconv = HypergraphConv(
    INPUT_DIM,
    OUTPUT_DIM
).to(DEVICE)

output = hgconv(
    dummy_features,
    G
)

print()

print("===================================")
print("Input Feature Shape :", dummy_features.shape)
print("Output Feature Shape:", output.shape)
print("===================================")

# ==========================================================
# LiteQ-STHNet - PART 5A-1.2
# Spatial Attention Module
# ==========================================================

import torch
import torch.nn as nn
import torch.nn.functional as F

# ==========================================================
# SPATIAL ATTENTION MODULE
# ==========================================================

class SpatialAttention(nn.Module):

    def __init__(self,
                 feature_dim=256):

        super(SpatialAttention, self).__init__()

        self.query = nn.Linear(
            feature_dim,
            feature_dim
        )

        self.key = nn.Linear(
            feature_dim,
            feature_dim
        )

        self.value = nn.Linear(
            feature_dim,
            feature_dim
        )

        self.softmax = nn.Softmax(dim=-1)

        self.scale = feature_dim ** 0.5

    def forward(self, x):

        # x : (N, Feature)

        Q = self.query(x)

        K = self.key(x)

        V = self.value(x)

        # Attention Score
        score = torch.matmul(
            Q,
            K.transpose(0,1)
        )

        score = score / self.scale

        attention = self.softmax(score)

        output = torch.matmul(
            attention,
            V
        )

        return output, attention

# ==========================================================
# TEST
# ==========================================================

NUM_NODES = 100

FEATURE_DIM = 256

dummy = torch.randn(
    NUM_NODES,
    FEATURE_DIM
)

spatial_attention = SpatialAttention(
    FEATURE_DIM
)

out, attn = spatial_attention(dummy)

print("=================================")
print("Input Shape      :", dummy.shape)
print("Output Shape     :", out.shape)
print("Attention Shape  :", attn.shape)
print("=================================")

print("\nSample Attention Matrix")

print(attn[:5,:5])

# ==========================================================
# LiteQ-STHNet - PART 5A-1.3
# Temporal Attention Module
# ==========================================================

import torch
import torch.nn as nn
import torch.nn.functional as F

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ==========================================================
# TEMPORAL ATTENTION
# ==========================================================

class TemporalAttention(nn.Module):

    def __init__(self,
                 feature_dim=256,
                 hidden_dim=256):

        super(TemporalAttention, self).__init__()

        self.query = nn.Linear(feature_dim, hidden_dim)

        self.key = nn.Linear(feature_dim, hidden_dim)

        self.value = nn.Linear(feature_dim, hidden_dim)

        self.softmax = nn.Softmax(dim=-1)

        self.scale = hidden_dim ** 0.5

    def forward(self, x):

        """
        x : (Batch, Time, Feature)
        """

        Q = self.query(x)

        K = self.key(x)

        V = self.value(x)

        attention = torch.matmul(

            Q,

            K.transpose(1,2)

        )

        attention = attention / self.scale

        attention = self.softmax(attention)

        output = torch.matmul(

            attention,

            V

        )

        return output, attention

# ==========================================================
# TEMPORAL POOLING
# ==========================================================

class TemporalPooling(nn.Module):

    def __init__(self):

        super().__init__()

    def forward(self, x):

        return torch.mean(x, dim=1)

# ==========================================================
# TEST MODULE
# ==========================================================

BATCH = 8

TIME_STEPS = 12

FEATURE_DIM = 256

dummy = torch.randn(

    BATCH,

    TIME_STEPS,

    FEATURE_DIM

).to(DEVICE)

temporal_attention = TemporalAttention(

    feature_dim=FEATURE_DIM,

    hidden_dim=FEATURE_DIM

).to(DEVICE)

pool = TemporalPooling()

output, attention = temporal_attention(dummy)

pooled = pool(output)

print()

print("==========================================")

print("Input Shape        :", dummy.shape)

print("Attention Shape    :", attention.shape)

print("Output Shape       :", output.shape)

print("Pooled Shape       :", pooled.shape)

print("==========================================")

print()

print("Sample Attention Matrix")

print(attention[0][:5, :5])

# ==========================================================
# LiteQ-STHNet - PART 5A-2.1
# Lite-ST-HGNN Block
# ==========================================================

import torch
import torch.nn as nn
import torch.nn.functional as F

# ==========================================================
# Lite-ST-HGNN Block
# ==========================================================

class LiteSTHGNNBlock(nn.Module):

    def __init__(self,
                 feature_dim=256,
                 dropout=0.30):

        super(LiteSTHGNNBlock, self).__init__()

        # Hypergraph Convolution
        self.hgconv = HypergraphConv(
            feature_dim,
            feature_dim,
            dropout
        )

        # Spatial Attention
        self.spatial = SpatialAttention(
            feature_dim
        )

        # Temporal Attention
        self.temporal = TemporalAttention(
            feature_dim,
            feature_dim
        )

        # Layer Normalization
        self.norm1 = nn.LayerNorm(feature_dim)

        self.norm2 = nn.LayerNorm(feature_dim)

        # Feed Forward Network
        self.ffn = nn.Sequential(

            nn.Linear(feature_dim,
                      feature_dim * 2),

            nn.ReLU(),

            nn.Dropout(dropout),

            nn.Linear(feature_dim * 2,
                      feature_dim)

        )

        self.dropout = nn.Dropout(dropout)

    def forward(self,
                x,
                G):

        # ---------------------------------------
        # Hypergraph Convolution
        # ---------------------------------------

        h = self.hgconv(
            x,
            G
        )

        # ---------------------------------------
        # Spatial Attention
        # ---------------------------------------

        spatial_out, spatial_weight = self.spatial(
            h
        )

        h = h + spatial_out

        h = self.norm1(h)

        # ---------------------------------------
        # Temporal Attention
        # ---------------------------------------

        temp_input = h.unsqueeze(0)

        temporal_out, temporal_weight = self.temporal(
            temp_input
        )

        temporal_out = temporal_out.squeeze(0)

        h = h + temporal_out

        h = self.norm2(h)

        # ---------------------------------------
        # Feed Forward
        # ---------------------------------------

        ff = self.ffn(h)

        h = h + ff

        h = self.dropout(h)

        return h, spatial_weight, temporal_weight


# ==========================================================
# TEST BLOCK
# ==========================================================

NUM_NODES = G.shape[0]

FEATURE_DIM = 256

dummy_feature = torch.randn(

    NUM_NODES,

    FEATURE_DIM

).to(DEVICE)

block = LiteSTHGNNBlock(

    feature_dim=FEATURE_DIM,

    dropout=0.30

).to(DEVICE)

output,

spatial_att,

temporal_att = block(

    dummy_feature,

    G

)

print()

print("========================================")

print("Input Shape          :", dummy_feature.shape)

print("Output Shape         :", output.shape)

print("Spatial Attention    :", spatial_att.shape)

print("Temporal Attention   :", temporal_att.shape)

print("========================================")

# ==========================================================
# LiteQ-STHNet - PART 5A-2.2
# Complete Lite-ST-HGNN Network
# ==========================================================

import torch
import torch.nn as nn
import torch.nn.functional as F

# ==========================================================
# Lite-ST-HGNN
# ==========================================================

class LiteSTHGNN(nn.Module):

    def __init__(self,
                 input_dim=256,
                 hidden_dim=256,
                 num_blocks=3,
                 num_classes=4,
                 dropout=0.30):

        super(LiteSTHGNN, self).__init__()

        self.input_proj = nn.Linear(
            input_dim,
            hidden_dim
        )

        # Stack Lite-ST-HGNN Blocks
        self.blocks = nn.ModuleList()

        for _ in range(num_blocks):

            self.blocks.append(

                LiteSTHGNNBlock(

                    feature_dim=hidden_dim,

                    dropout=dropout

                )

            )

        self.classifier = nn.Sequential(

            nn.Linear(hidden_dim,128),

            nn.ReLU(),

            nn.Dropout(dropout),

            nn.Linear(128,64),

            nn.ReLU(),

            nn.Dropout(dropout),

            nn.Linear(64,num_classes)

        )

    def forward(self,x,G):

        x = self.input_proj(x)

        spatial_maps = []

        temporal_maps = []

        for block in self.blocks:

            x, spatial, temporal = block(x,G)

            spatial_maps.append(spatial)

            temporal_maps.append(temporal)

        # Global Node Pooling
        graph_feature = torch.mean(x,dim=0)

        logits = self.classifier(graph_feature)

        return logits,x,spatial_maps,temporal_maps

# ==========================================================
# CREATE MODEL
# ==========================================================

NUM_CLASSES = 4

model = LiteSTHGNN(

    input_dim=256,

    hidden_dim=256,

    num_blocks=3,

    num_classes=NUM_CLASSES,

    dropout=0.30

).to(DEVICE)

print(model)

# ==========================================================
# TEST
# ==========================================================

NUM_NODES = G.shape[0]

dummy = torch.randn(

    NUM_NODES,

    256

).to(DEVICE)

logits,node_features,spatial,temporal = model(

    dummy,

    G

)

print()

print("========================================")

print("Node Feature Shape :",node_features.shape)

print("Logits Shape       :",logits.shape)

print("Spatial Maps       :",len(spatial))

print("Temporal Maps      :",len(temporal))

print("========================================")

# ==========================================================
# LiteQ-STHNet - PART 5B-1
# Dataset Preparation + Training Setup
# ==========================================================

import os
import numpy as np
import torch
import torch.nn as nn

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

from torch.utils.data import Dataset
from torch.utils.data import DataLoader

# ==========================================================
# DEVICE
# ==========================================================

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ==========================================================
# LOAD FEATURES
# ==========================================================

FEATURE_PATH = "/content/encoded/quantum_features.npy"

LABEL_PATH = "/content/processed/processed_text.csv"

X = np.load(FEATURE_PATH)

print("Feature Shape :", X.shape)

# ==========================================================
# LOAD LABELS
# ==========================================================

import pandas as pd

df = pd.read_csv(LABEL_PATH)

# Change this column according to your dataset
LABEL_COLUMN = "label"

labels = df[LABEL_COLUMN].values[:len(X)]

encoder = LabelEncoder()

y = encoder.fit_transform(labels)

NUM_CLASSES = len(np.unique(y))

print("Classes :", encoder.classes_)

# ==========================================================
# TRAIN TEST SPLIT
# ==========================================================

X_train, X_test, y_train, y_test = train_test_split(

    X,

    y,

    test_size=0.20,

    random_state=42,

    stratify=y

)

print()

print("Training Samples :", len(X_train))

print("Testing Samples  :", len(X_test))

# ==========================================================
# DATASET
# ==========================================================

class MentalDataset(Dataset):

    def __init__(self, x, y):

        self.x = torch.tensor(

            x,

            dtype=torch.float32

        )

        self.y = torch.tensor(

            y,

            dtype=torch.long

        )

    def __len__(self):

        return len(self.x)

    def __getitem__(self, idx):

        return self.x[idx], self.y[idx]

# ==========================================================
# DATALOADER
# ==========================================================

train_dataset = MentalDataset(

    X_train,

    y_train

)

test_dataset = MentalDataset(

    X_test,

    y_test

)

train_loader = DataLoader(

    train_dataset,

    batch_size=32,

    shuffle=True

)

test_loader = DataLoader(

    test_dataset,

    batch_size=32,

    shuffle=False

)

# ==========================================================
# MODEL
# ==========================================================

model = LiteSTHGNN(

    input_dim=256,

    hidden_dim=256,

    num_blocks=3,

    num_classes=NUM_CLASSES,

    dropout=0.30

).to(DEVICE)

# ==========================================================
# LOSS
# ==========================================================

criterion = nn.CrossEntropyLoss()

# ==========================================================
# OPTIMIZER
# ==========================================================

optimizer = torch.optim.Adam(

    model.parameters(),

    lr=1e-3,

    weight_decay=1e-5

)

# ==========================================================
# LR Scheduler
# ==========================================================

scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(

    optimizer,

    mode="max",

    factor=0.5,

    patience=5

)

print()

print("====================================")

print("Training Ready")

print("Train Batches :", len(train_loader))

print("Test Batches  :", len(test_loader))

print("Classes       :", NUM_CLASSES)

print("====================================")